project:
  title: "My Awesome Report using VSCode Devcontainers"
  execute-dir: project
  output-dir: _output

editor: source
execute:
  echo: true

format:
  typst:
    author: "Michael Thomas"
    template-partials:
      - assets/typst-show.typ
      - assets/typst-template.typ
    toc: true
    lof: true
    lot: true
    background-img:
      path: assets/www/background.jpg
    header-logo:
      path: assets/www/logo.jpg

mermaid:
  theme: default
