project:
  title: "My Awesome Report using VSCode Devcontainers"
  execute-dir: project
  output-dir: _output

editor: source
execute:
  echo: true

format:
  typst:
    toc: true
    number-sections: true

mermaid:
  theme: default
